### ISSUE TITLE
Number of key-frames

### ISSUE THREAD

**Issue by kovanic** [NVlabs/RVT#16]
Hi! Thank you for an interesting work. I'm trying to train RVT on real data. Could you please tell how much key-frames were collected for a real episode on average?

**Comment by imankgoyal** [comment]
Hi @kovanic,

Thanks for your interest in RVT. So for real data, we collected 51 training demos and around 4-5 keyframes per demo. 

Also, since you are training on the real data, we simultaneously record the RGB-D stream from the camera
during the robot’s motion to the targets. And we also use the intermediate frames while learning. That is given an intermediate frame, predict the next keypooint.

**Comment by kovanic** [comment]
Thank you for your response!
